### ISSUE TITLE
Crash on Rightclick with duct in hand

### ISSUE THREAD

**Issue by WTFFFS** [WingsOfLife/DynamicLiquidTanks_v2.0#17]
I get a client only crash when I right click on a tank block with a duct in hand (possibly other items but the duct definitely), version 0.0.5a, crash report:
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 14/01/14 7:04 PM
Description: Exception in world tick

java.lang.NullPointerException
    at doc.mods.dynamictanks.client.gui.GuiController.func_73866_w_(GuiController.java:61)
    at net.minecraft.client.gui.GuiScreen.func_73872_a(SourceFile:94)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73872_a(GuiContainer.java:99)
    at net.minecraft.client.Minecraft.func_71373_a(Minecraft.java:732)
    at cpw.mods.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:398)
    at cpw.mods.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:334)
    at cpw.mods.fml.common.network.NetworkRegistry.openLocalGui(NetworkRegistry.java:328)
    at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:357)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2480)
    at cpw.mods.fml.common.network.OpenGuiPacket.execute(OpenGuiPacket.java:67)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleFMLPacket(FMLNetworkHandler.java:116)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:81)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1651)
    at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
    at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:99)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1930)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

As stated it only crashes the client not the server, it appears to be an issue with trying to connect a duct and open the tank gui at the same time. (hope that is enough fo the crash report if not I'll pastebin the full report (if i can remember my login lol)

**Comment by WingsOfLife** [comment]
Fixed in next version.
