### ISSUE TITLE
Server Crashes when removing and placing tank controller.

### ISSUE THREAD

**Issue by Ealendir** [WingsOfLife/DynamicLiquidTanks_v2.0#20]
When a tank controller is removed and then placed again my server crashes (FTB Monster 1.0.11)
Here the errormessage:

2014-03-01 10:49:14 [SEVERE] Encountered an unexpected exception ReportedException
net.minecraft.util.ReportedException: Ticking tile entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:674)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:276)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.lang.ClassCastException: TileMultipart_cmp$$24 cannot be cast to doc.mods.dynamictanks.tileentity.ControllerTileEntity
    at doc.mods.dynamictanks.tileentity.TankTileEntity.searchForController(TankTileEntity.java:180)
    at doc.mods.dynamictanks.tileentity.TankTileEntity.func_70316_g(TankTileEntity.java:221)
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
    ... 4 more

it appears only to happen when i'm morphed into another form (Morph-Beta-0.7.0)

**Comment by WingsOfLife** [comment]
Fixed in 0.0.8
