### ISSUE TITLE
Server crash when placing upgrade block

### ISSUE THREAD

**Issue by LemADEC** [WingsOfLife/DynamicLiquidTanks_v2.0#21]
With 0.0.7a, upgrade block isn't craftable but it can still be spawned in creative or recover from existing build. When placing it on tank, it'll crash the server.
Sneak placing it doesn't crash.

```
---- Minecraft Crash Report ----
// My bad.

Time: 3/4/14 9:13 PM
Description: Ticking tile entity

java.lang.RuntimeException: You cannot send a bare packet without a target on the server!
    at cpw.mods.fml.server.FMLServerHandler.sendPacket(FMLServerHandler.java:173)
    at cpw.mods.fml.common.network.PacketDispatcher.sendPacketToServer(PacketDispatcher.java:38)
    at doc.mods.dynamictanks.packets.PacketHandler.sendPacketWithInt(PacketHandler.java:142)
    at doc.mods.dynamictanks.tileentity.UpgradeTileEntity.updateController(UpgradeTileEntity.java:101)
    at doc.mods.dynamictanks.tileentity.UpgradeTileEntity.shareInformation(UpgradeTileEntity.java:120)
    at doc.mods.dynamictanks.tileentity.UpgradeTileEntity.func_70316_g(UpgradeTileEntity.java:274)
    at net.minecraft.world.World.func_72939_s(World.java:2782)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:883)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at cpw.mods.fml.server.FMLServerHandler.sendPacket(FMLServerHandler.java:173)
    at cpw.mods.fml.common.network.PacketDispatcher.sendPacketToServer(PacketDispatcher.java:38)
    at doc.mods.dynamictanks.packets.PacketHandler.sendPacketWithInt(PacketHandler.java:142)
    at doc.mods.dynamictanks.tileentity.UpgradeTileEntity.updateController(UpgradeTileEntity.java:101)
    at doc.mods.dynamictanks.tileentity.UpgradeTileEntity.shareInformation(UpgradeTileEntity.java:120)
    at doc.mods.dynamictanks.tileentity.UpgradeTileEntity.func_70316_g(UpgradeTileEntity.java:274)

-- Tile entity being ticked --
Details:
    Name: dynamictanks.tile.upgradeTile // doc.mods.dynamictanks.tileentity.UpgradeTileEntity
    Block type: ID #3196 (tile.dynamictanks.block.upgradeModule // doc.mods.dynamictanks.block.BlockUpgrade)
    Block data value: 4 / 0x4 / 0b0100
    Block location: World: (462,70,894), Chunk: (at 14,4,14 in 28,55; contains blocks 448,0,880 to 463,255,895), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
    Actual block type: ID #3196 (tile.dynamictanks.block.upgradeModule // doc.mods.dynamictanks.block.BlockUpgrade)
    Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2782)

-- Affected level --
Details:
    Level name: Pyrotech
    All players: 2 total; (cut)
    Chunk stats: ServerChunkCache: 1336 Drop: 0
    Level seed: 5829238858090728412
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (375,70,390), Chunk: (at 7,4,6 in 23,24; contains blocks 368,0,384 to 383,255,399), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 61536064 game time, 13889979 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 14481 (now: false), thunder time: 18006 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:883)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
```

**Comment by WingsOfLife** [comment]
Fixed in 0.0.8
