### ISSUE TITLE
 Rendering Tile Entity

### ISSUE THREAD

**Issue by donbubu** [WingsOfLife/DynamicLiquidTanks_v2.0#25]
the client crash if i sneak and look in the direction to the controller where is behind some blocks so i can't see the controller. only on some position and only if i sneak.

 Caused by: java.lang.ClassCastException: TileMultipart_cmp$$28 cannot be cast to doc.mods.dynamictanks.tileentity.ControllerTileEntity
 at doc.mods.dynamictanks.client.render.RenderController.func_76894_a(RenderController.java:20)
 at net.minecraft.client.renderer.tileentity.TileEntityRenderer.func_76949_a(SourceFile:106)
 ... 13 more
  ---- Minecraft Crash Report ----
  // Quite honestly, I wouldn't worry myself about that.

  Time: 03.05.14 19:10
  Description: Rendering Tile Entity

  java.lang.ClassCastException: TileMultipart_cmp$$28 cannot be cast to doc.mods.dynamictanks.tileentity.ControllerTileEntity
   at doc.mods.dynamictanks.client.render.RenderController.func_76894_a(RenderController.java:20)
   at net.minecraft.client.renderer.tileentity.TileEntityRenderer.func_76949_a(SourceFile:106)
   at net.minecraft.client.renderer.tileentity.TileEntityRenderer.func_76950_a(SourceFile:98)
   at net.minecraft.client.renderer.RenderGlobal.func_72713_a(RenderGlobal.java:597)
   at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1509)
   at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1119)
   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:946)
   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
   at net.minecraft.client.main.Main.main(SourceFile:101)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   at java.lang.reflect.Method.invoke(Unknown Source)
   at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
   at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by WingsOfLife** [comment]
Old version. Fixed
