### ISSUE TITLE
Render errors and NullPointerException after replacing tank controller

### ISSUE THREAD

**Issue by Zarathul** [WingsOfLife/DynamicLiquidTanks_v2.0#6]
Steps to reproduce the render bug:
1. Place a Tank Block
2. Place a Tank Controller connecting with the Tank Block
3. Fill the Tank Block with a liquid bucket of your choice (doesn't have to be full)
4. Destroy the Tank Controller
5. Place a NEW Tank Controller in the exact same location as the old one
6. Fill the Tank Block. The Tank will now be rendered completely full after inserting only 1 bucket of liquid.

Steps to reproduce the NullPointerException:
Steps 1-4 are the same as above
5. Place a NEW Tank Controller on a different side of the Tank Block
6. Trying to fill the Tank with any fluid bucket will now result in a crash.

Both bugs appear regardless of size and shape of the tank.

![1](https://f.cloud.github.com/assets/6231628/1791702/538f1eb4-6992-11e3-9cbc-23e6c19634f8.png)
![2](https://f.cloud.github.com/assets/6231628/1791701/538f067c-6992-11e3-9e7c-a623fa59b6c7.png)
![3](https://f.cloud.github.com/assets/6231628/1791703/538f70e4-6992-11e3-99de-a360cd4a3a74.png)
![4](https://f.cloud.github.com/assets/6231628/1791704/5391117e-6992-11e3-8ab6-c6cccc9193a3.png)
![5](https://f.cloud.github.com/assets/6231628/1791705/5393ad76-6992-11e3-8d64-51b2ac110d5c.png)
![6](https://f.cloud.github.com/assets/6231628/1791706/53a57bc8-6992-11e3-9967-021efeb18cec.png)

```
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 20.12.13 17:13
Description: Unexpected error

java.lang.NullPointerException
    at doc.mods.dynamictanks.block.BlockTank.func_71903_a(BlockTank.java:162)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:371)
    at net.minecraft.client.Minecraft.func_71402_c(Minecraft.java:1390)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1868)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at doc.mods.dynamictanks.block.BlockTank.func_71903_a(BlockTank.java:162)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:371)
    at net.minecraft.client.Minecraft.func_71402_c(Minecraft.java:1390)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Zarathul'/0, l='MpServer', x=-1333,49, y=57,62, z=657,89]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-1331,4,651), Chunk: (at 13,0,11 in -84,40; contains blocks -1344,0,640 to -1329,255,655), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
    Level time: 17114 game time, 4358 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 2 total; [EntityItem['item.tile.dynamictanks.block.controller'/320031, l='MpServer', x=-1335,84, y=56,13, z=654,75], EntityClientPlayerMP['Zarathul'/0, l='MpServer', x=-1333,49, y=57,62, z=657,89]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:863)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1508244552 bytes (1438 MB) / 2441543680 bytes (2328 MB) up to 3817799680 bytes (3640 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2G -Xmx4G
    AABB Pool Size: 130 (7280 bytes; 0 MB) allocated, 2 (112 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.45.953 Minecraft Forge 9.11.1.953 4 mods loaded, 4 mods active
    mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.45.953} [Forge Mod Loader] (minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.953} [Minecraft Forge] (minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    dynamictanks{1.0} [Dynamic Liquid Tanks 2] (DynamicTanks2_v0.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.6.4-Forge9.11.1.953
    LWJGL: 2.9.0
    OpenGL: GeForce GTX 660 Ti/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 148 (8288 bytes; 0 MB) allocated, 18 (1008 bytes; 0 MB) used
```

**Comment by WingsOfLife** [comment]
Fixed in next version
