### ISSUE TITLE
Crash when placing DLT liquids in creative

### ISSUE THREAD

**Issue by Zarathul** [WingsOfLife/DynamicLiquidTanks_v2.0#7]
When disabling DLT liquids in the config file ("enable fluids") buckets and chalices with these liquids are still available by using the vanilla creative gui, cheat commands or NEI. Using any of this items results in a IndexOutOfBoundsException.
DLT liquids buckets and chalices should not be usable when "enable fluids" is set to false. Optionaly it would be nice if they didnt even show up in the creative gui and NEI.

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 20.12.13 17:59
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at doc.mods.dynamictanks.items.BucketPotion.tryPlaceContainedLiquid(BucketPotion.java:191)
    at doc.mods.dynamictanks.items.BucketPotion.func_77659_a(BucketPotion.java:173)
    at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:177)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:428)
    at net.minecraft.client.Minecraft.func_71402_c(Minecraft.java:1417)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1868)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at doc.mods.dynamictanks.items.BucketPotion.tryPlaceContainedLiquid(BucketPotion.java:191)
    at doc.mods.dynamictanks.items.BucketPotion.func_77659_a(BucketPotion.java:173)
    at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:177)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:428)
    at net.minecraft.client.Minecraft.func_71402_c(Minecraft.java:1417)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Zarathul'/0, l='MpServer', x=117,50, y=57,62, z=142,50]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (123,4,133), Chunk: (at 11,0,5 in 7,8; contains blocks 112,0,128 to 127,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 175 game time, 175 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 1 total; [EntityClientPlayerMP['Zarathul'/0, l='MpServer', x=117,50, y=57,62, z=142,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:863)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1991177752 bytes (1898 MB) / 2594897920 bytes (2474 MB) up to 3817799680 bytes (3640 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2G -Xmx4G
    AABB Pool Size: 10595 (593320 bytes; 0 MB) allocated, 3 (168 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.45.953 Minecraft Forge 9.11.1.953 4 mods loaded, 4 mods active
    mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.45.953} [Forge Mod Loader] (minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.953} [Minecraft Forge] (minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    dynamictanks{1.0} [Dynamic Liquid Tanks 2] (DynamicTanks2_v0.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.6.4-Forge9.11.1.953
    LWJGL: 2.9.0
    OpenGL: GeForce GTX 660 Ti/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 57 (3192 bytes; 0 MB) allocated, 30 (1680 bytes; 0 MB) used
```

**Comment by WingsOfLife** [comment]
Though this should be common sense, seeing as they cannot be obtained without "cheats", it will be fixed in the next version.
